#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=bld.path.ant_glob('**/*.cpp'),
    target='bitter_tests',
    use=['endian_includes','bitter_includes', 'gtest'])
