#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx',
            source='bitfield_simple_writer.cpp',
            target='bitfield_simple_writer',
            use=['bitter_includes'])
